name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t my-app .
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.sreyakunni }}
        password: ${{ secrets."Rohith@1999 "}}
    - name: Push the Docker image
      run: |
        docker tag my-app ${{ secrets.DOCKER_USERNAME }}/my-app
        docker push ${{ secrets.DOCKER_USERNAME }}/my-app
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.54.163.189.143 }}
        username: ${{ secrets.ec2-user }}
        key: ${{ secrets.nodejs_app }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-app
          docker stop my-app || true
          docker rm my-app || true
          docker run -d --name my-app -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/my-app
