name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t my-app .
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        Docker_Hub_Username: sreyakunni
        Docker_Hub_Password: Rohith@1999
        username: ${{ secrets.Docker_Hub_Username }}
        password: ${{ secrets.Docker_Hub_Password }}
    - name: Push the Docker image
      run: |
        docker tag my-app ${{ secrets.DOCKER_USERNAME }}/my-app
        docker push ${{ secrets.DOCKER_USERNAME }}/my-app
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        EC2_HOST: 54.163.189.143
        EC2_USERNAME: ec2-user
        EC2_KEY: nodejs_app
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.ec2-user }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-app
          docker stop my-app || true
          docker rm my-app || true
          docker run -d --name my-app -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/my-app
